# Docker-compose wrapper for rundler-hc prototype. This version defines
# two services, the bundler and a placeholder "offchain" JSON-RPC service.
# These could be decoupled and run on separate machines but they are packaged
# together here for convenience.
#
# The contract addresses are obtained by manually deploying the contracts,
# and must be updated when the contracts are changed. The present implementation
# does not put them behind a proxy.
#
# There are additional private keys:
#  - A bundler private key for the EOA through which it submits transactions
#  - An owner which generates signatures for the system-level Hybrid Account
#    which is used to insert error responses and clean up stale cache entries
#  - An owner which generates signatures for the offchain JSON-RPC responses

services:
  rundler-hc:
    depends_on:
      - kms
    build:
      context: ..
      dockerfile: Dockerfile
    image: rundler-hc:latest
    environment:
      HC_HELPER_ADDR:  ${HC_HELPER_ADDR}  # Deployed contract address
      HC_SYS_ACCOUNT:  ${HC_SYS_ACCOUNT}  # Deployed contract address
      HC_SYS_OWNER:    ${HC_SYS_OWNER}    # Owner/Signer for HC_SYS_ACCOUNT
      HC_SYS_PRIVKEY:  ${HC_SYS_PRIVKEY}  # Owner/Signer for HC_SYS_ACCOUNT
      NODE_HTTP:       ${NODE_HTTP}       # Replica/Sequencer URL
      CHAIN_ID:        ${CHAIN_ID}        # Chain ID
      RPC_PORT:        3300               # RPC port to submit into Bundler
      SIGNER_PRIVATE_KEYS:    ${SIGNER_PRIVATE_KEYS}    # Keys for bundler EOA
      SIGNER_AWS_KMS_KEY_IDS: ${SIGNER_AWS_KMS_KEY_IDS} # KMS key IDs (instead of private keys)
      BUILDER_KMS_REGION:     ${BUILDER_KMS_REGION}     # KMS region
      BUILDER_KMS_URL:        "http://kms:8080"         # Local KMS URL
      AWS_ACCESS_KEY_ID:      "test"                    # AWS credentials
      AWS_SECRET_ACCESS_KEY:  "test"                    # AWS credentials
    ports:
      - 3300:3300
#    command: >
#      --disable_entry_point_v0_6

  offchain-rpc:
    build:
      context: .
      dockerfile: Dockerfile.offchain-rpc
    image: offchain-rpc:latest
    environment:
      HC_HELPER_ADDR:    ${HC_HELPER_ADDR}     # Deployed contract address
      ENTRY_POINTS:      ${ENTRY_POINTS}       # Deployed contract address (note: only supports a single addr here)
      CHAIN_ID:          ${CHAIN_ID}           # Chain ID
      OC_LISTEN_PORT:    1234                  # Port for RPC server
      OC_HYBRID_ACCOUNT: ${OC_HYBRID_ACCOUNT}  # Deployed contract address
      OC_OWNER:          ${OC_OWNER}           # Owner/Signer for OC_HYBRID_ACCOUNT
      OC_PRIVKEY:        ${OC_PRIVKEY}         # Owner/Signer for OC_HYBRID_ACCOUNT
      OC_NODE_HTTP:      ${OC_NODE_HTTP}       # RPC node for VRF
      OC_RANDOM_SECRET:  ${OC_RANDOM_SECRET}   # VRF secret
      OC_RANDOM_KEYHASH: ${OC_RANDOM_KEYHASH}  # VRV public keyhash

    ports:
      - 1234:1234
  kms:
    deploy:
      replicas: 0  # Disabled by default, set 1 to enable
    image: nsmithuk/local-kms  # https://github.com/nsmithuk/local-kms
    environment:
      KMS_REGION: us-east-1
    volumes:
      - ./kms-init:/init
      - ./kms-data:/data
    ports:
      - 4566:8080
