[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache'
solc_version = '0.8.26'
optimizer = true
optimizer_runs = 200
evm_version = 'paris'
cbor_metadata = true
allow_internal_expect_revert = true
via_ir = true

remappings = [
    'forge-std/=lib/forge-std/src',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
]

[etherscan]
boba_sepolia = {key = "verifyContract", chain = 28882, url = "https://api.routescan.io/v2/network/testnet/evm/28882/etherscan" }
boba_mainnet = {key = "verifyContract", chain = 288, url = "https://api.routescan.io/v2/network/mainnet/evm/288/etherscan" }
